### ISSUE TITLE
Missing assets directory

### ISSUE THREAD

**Issue by cliftonscott** [creativetimofficial/ct-material-dashboard-pro-laravel#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

The documentation says there is an assets directory.

# Current Behavior

What is the current behavior?

assets directory is missing. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Ghitu** [comment]
Hello, thank you for the feedback!

We worked without an assets directory.
If you want you can create one yourself, you can find all the assets in the public folder.

Can you please help us out with a link or a printscreen where the documentation says there is an assets directory?

Let us know if we can help you further.

Alin
