### ISSUE TITLE
JQuery Ajax request doesn't work

### ISSUE THREAD

**Issue by laravelhelp2** [creativetimofficial/ct-material-dashboard-pro-laravel#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

JQuery Ajax request should work

# Current Behavior

JQuery Ajax request doesn't work properly 

# Failure Information (for bugs)

## Steps to Reproduce

1. Put a simple JQuery Ajax request in a test.blade.php template below @push('js'):

```
   $.ajax({
   type: 'POST',
   url: '/ajaxRequest',
   data: {name:name, password:password, email:email},
   success: function( data ) {
    alert(1);
   },
   error: function(xhr, status, error) {
    alert(2);
   },
   dataType: 'text'
});
```

2. Load blade template
3. No JQuery Ajax is loaded
4. If I put that simple JQuery ajax call to a plain blade template (without importing material-pro files) it works.

## Context

* Device: Desktop
* Operating System: Linux, Windows
* Browser and Version: Firefox, Chrome

## Failure Logs

na.

**Comment by teamupdivision** [comment]
Hello, can you please send the contents of the whole file?
Thank you

**Comment by laravelhelp2** [comment]
tested again and it works. It was my fault with code. Thanks
