### ISSUE TITLE
Missing material_select for refreshing the select drop-down

### ISSUE THREAD

**Issue by samit-at-techverita** [creativetimofficial/ct-material-dashboard-pro-laravel#11]
I have the latest version. I am using Ajax to query backend and update the select drop-down based on user input. However, the select box is not displaying the updated content though JQuery shows that innerText has got the elements. Call to material_select says it is not a function. What is missing out here?

**Comment by teamupdivision** [comment]
Hello, can you please send us a sample of your code?

**Comment by samit-at-techverita** [comment]
Here are the details. The call to material_select() fails.

This the first select box where the user selects nationality:
<div class="form-group">
   {{ Form::select('nationality_id', $personNationality, null, ['id' => 'nationality_id', 'class' => 'selectpicker', 'data-style' => 'select-with-transition', 'data-size' => '7', 'title' => 'Nationality', 'required' => 'true']) }}
</div>

This is the second select box which should get updated based on what user select in the first box:

<div class="form-group">
   {{ Form::select('category_id', ['None'], null, ['id' => 'category_id', 'class' => 'selectpicker', 'data-style' => 'select-with-transition', 'data-size' => '7', 'title' => 'Category', 'required' => 'true']) }}
</div>


The following script is written below the blade:

<script>
       $(function() {
           $('select[name=nationality_id]').change(function() {
               var url = '{{ url('nationality') }}/' + $(this).val() + '/categories/';

               $.get(url, function(data) {
                   var select = $('form select[name=category_id]');
                   select.empty();
                   $.each(data,function(key, value) {
                       select.append("<option value="+ value.id + "> " + value.category_name + "</option>");
                   });

                   $('#category_id').material_select();
               });
           });
       });

</script>


regards
Samit Ray

**Comment by samit-at-techverita** [comment]
Oh - found the solution. Using selectpicker("refresh") worked. Thanks

**Comment by teamupdivision** [comment]
Good to hear
