### ISSUE TITLE
Navbar placement sticky-bottom? / documentation not complete

### ISSUE THREAD

**Issue by aefika** [creativetimofficial/ct-material-dashboard-pro-laravel#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
I'm trying to place the navbar at the bottom, using position: sticky
Documentation refers to position utilities, but that link doesn't work: https://material-dashboard-pro-laravel.creative-tim.com/docs/2.0/utilities/position/

# Current Behavior

What is the current behavior?
The documentation seems to indicate that only .sticky-top exists.
When using sticky-top the navbar doesn't stick (using chrome)

**Comment by groovemen** [comment]
Hello @aefika, 

Thank you for using our products, we have tested this link https://material-dashboard-pro-laravel.creative-tim.com/docs/2.0/utilities/position/ for both classes: **.sticky-top** and **.fixed-top** and it works as expected. All you have to do is to erase the `navbar-absolute` class from the navbar.

All the best, 
Stefan

**Comment by aefika** [comment]
Hello Stefan,

 

Thanks for the answer, the css choices works on html.

 

What doesn’t work for me is the link provided in the documentation:



 

Luis Nicho, Ing., MGP, PMP

Directeur des opérations

AEfika Services-conseil

 

T +1 (514) 258 6215

C  <mailto:luis.nicho@aefika.com> luis.nicho@aefika.com

 

 



OUTILS PRATIQUES SUR MESURE POUR

RÉVOLUTIONNER VOTRE TRAVAIL

 <http://www.aefika.com/> www.aefika.com

 

(SVP noter que je suis basé à Montréal et que mon fuseau horaire est UTC -05 :00)

**Comment by teamupdivision** [comment]
Hello, here is the correct link: https://getbootstrap.com/docs/4.4/utilities/position/
