### ISSUE TITLE
Install on existing app

### ISSUE THREAD

**Issue by bUniq-tech** [creativetimofficial/ct-material-dashboard-pro-laravel#14]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I have a laravel app already started and coded. I want to install your theme. I bought it but I want to install it without losing my current laravel app, so I cannot install your project standalone as in the doc. How can I install it in my current existing app? I need the components so I can add the views in my current webapp.

I'm using Laravel 5.8

**Comment by teamupdivision** [comment]
Hello and thanks for using our products!

The PRO version is a full Laravel project, it is not a theme. You cannot combine what you did in the previously with the Material PRO with a plug and play approach.

Let us know what exactly you did in your previous project and maybe we can help you out and copy some of the functionality on the Material PRO version.

Thank you

**Comment by bUniq-tech** [comment]
Hi,
I solved placing only the resources and the material folder inside public folder in my existing laravel. I don't care about the example pages, so I haven't included your default controllers, routes and other stuff. It's working, so it is enough to import the resources and public files in order to use the components.

**Comment by teamupdivision** [comment]
Glad things worked out.
Let us know if you find any issues.
All the best.
