### ISSUE TITLE
Default color

### ISSUE THREAD

**Issue by bUniq-tech** [creativetimofficial/ct-material-dashboard-pro-laravel#15]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Default color is rose. I'd like to set as default another color statically. How can I do it?

**Comment by teamupdivision** [comment]
Hello @bUniq-tech, thanks for using our products!
Please refer to this issue, let me know if this solves your problem.

All the best
