### ISSUE TITLE
Difficulty to set page template using Material Components

### ISSUE THREAD

**Issue by aefika** [creativetimofficial/ct-material-dashboard-pro-laravel#17]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I'm expecting to stablish an auth page layout with a specific structure: one navbar fixed-top, one sidebar left collapsible, and an additional navbar (called actionbar) fixed-bottom collapsible.
In addition, I need content to be split in content and content_aux, with content_aux collapsible.

See image as reference:
![image](https://user-images.githubusercontent.com/40780788/74090531-6178e580-4a7a-11ea-93f8-7c0c8c32998d.png)

# Current Behavior

I don't manage to get all elements to align using the documentation provided. Sidebar goes over navbars and collapsible doesn't work well. Here is the image result:
![image](https://user-images.githubusercontent.com/40780788/74090553-a8ff7180-4a7a-11ea-835a-f6d8f1f102f0.png)

My auth page template is:
```
<div class="wrapper ">
  @include('layouts.navbars.navs.auth')  
  @include('layouts.navbars.sidebar')
  <div class="main-panel"> 
    @yield('content')
    @include('layouts.footers.auth')
  </div>
  @include('layouts.navbars.action')
</div>
```

layouts.navbars.navs.auth:
`  <nav class="navbar navbar-expand-lg navbar-light navbar-absolute fixed-top">`
layouts.navbars.sidebar:
`<div class="sidebar" data-color="azure" data-background-color="black">`
layouts.navbars.action:
`<nav class="navbar fixed-bottom navbar-expand-lg navbar-light">`

What is the best way to use your current styles to achieve the expected behaivour

**Comment by teamupdivision** [comment]
Hello @aefika, thank you for using our products!

Please let us know if you find any bugs with the product. Unfortunately we cannot make on demand feature updates for the product to cover your immediate need. 
If you need development services, please go to: https://services.creative-tim.com/

All the best
