### ISSUE TITLE
Sweet Alert

### ISSUE THREAD

**Issue by TimmKnuth** [creativetimofficial/ct-material-dashboard-pro-laravel#19]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by TimmKnuth** [comment]
Hello,
I am trying to use SweetAlerts in my Table to delete a row. But the SweetAlert Popup shows just 2seconds and then it disappears. So my table data looks like this:

</td>
                                @can('manage-users', App\User::class)
                                    <td class="td-actions text-right">
                                        <form action="{{ route('projekte.destroy', $projekt->projNr) }}" method="post">
                                            @csrf
                                            @method('delete')
                                                <a rel="tooltip" class="btn btn-success btn-link" href="/Laravel/stiwaV2.3/public/projekte/{{$projekt->projNr}}/edit" data-original-title="" title="">
                                                    <i class="material-icons">edit</i>
                                                    <div class="ripple-container"></div>
                                                </a>

                                            <button type="button" class="btn btn-rose btn-fill" onclick="demo.showSwal('warning-message-and-cancel')">Try me!</button>
                                        </form>
                                    </td>
                                @endcan

**Comment by TimmKnuth** [comment]
Hello,
I am trying to use SweetAlerts to delete a Table row. But the SweetAlert shows just for a few seconds and then disappears. But the row is deleted. Here is my tabledata where i want to use the sweeetAlert:

<td class="td-actions text-right">
                                        <form action="{{ route('projekte.destroy', $projekt->projNr) }}" method="post">
                                            @csrf
                                            @method('delete')
                                                <a rel="tooltip" class="btn btn-success btn-link" href="/Laravel/stiwaV2.3/public/projekte/{{$projekt->projNr}}/edit" data-original-title="" title="">
                                                    <i class="material-icons">edit</i>
                                                    <div class="ripple-container"></div>
                                                </a>

                                            <button type="button" class="btn btn-rose btn-fill" onclick="demo.showSwal('warning-message-and-cancel')">Try me!</button>
                                        </form>
                                    </td>

**Comment by teamupdivision** [comment]
Hello, thanks for using our products!
When initializing sweetalert you need to give it a timer parameter, for example, for 5 seconds you need to have `timer: 5000`

All the best!
