### ISSUE TITLE
How to update from free version to pro version

### ISSUE THREAD

**Issue by shintaro-san** [creativetimofficial/ct-material-dashboard-pro-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?
I cannot upgrade to pro version from free version.

# Failure Information (for bugs)
I don't know how to do it.
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Ghitu** [comment]
Hello @shintaro-san, thank you for using our products!

What do you mean by upgrading from FREE to PRO, what exactly is not working?
Are you trying to use the codebase you worked on in the FREE version and use in the PRO version.

Thank you
Alin

**Comment by shintaro-san** [comment]
Thank you for your reply.

I installed free version by using the archive to my app.
It was successlly installed.

Then, I purchased the pro version and would like to appy it to the app.
But there is no instruction for that.

**Comment by Ghitu** [comment]
Hello, 

The free version is just a part of the Laravel project, while the PRO version is a full Laravel project. You cannot combine what you did in the FREE version with the PRO version you installed with a plug and play approach. 

Let us know what exactly you did on top of the FREE version and maybe we can help you out and copy some of the functionality on the PRO version.

Thank you
Alin
