### ISSUE TITLE
Is this available for vuejs?

### ISSUE THREAD

**Issue by aefika** [creativetimofficial/ct-material-dashboard-pro-laravel#20]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

This is not a bug, it's a question

# Current Behavior

What is the current behavior?
Is this package available for vuejs?
I have a mixed Laravel and vue site where I need to have the same styling
1. How can I get the vue version for material-dashboard pro?

2. I've found something very similar. Is this you guys: https://mdbootstrap.com/docs/vue/getting-started/download/

**Comment by teamupdivision** [comment]
Hello, thanks for using our products.
A Laravel + Vue package is not available yet. We'll probably be working on one this year.

There are to non-Laravel Vue.js packages:
https://www.creative-tim.com/product/vue-material-dashboard-pro
https://www.creative-tim.com/product/vuetify-material-dashboard-pro
