### ISSUE TITLE
inline panels in timeline

### ISSUE THREAD

**Issue by bUniq-tech** [creativetimofficial/ct-material-dashboard-pro-laravel#21]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

https://demos.creative-tim.com/material-dashboard-pro/examples/pages/timeline.html

I'd like to have two panels in same line to the timeline, one to the left and one to the right (inverted).
Is there some preferred way to do this? Or should I customize it with custom CSS?

**Comment by teamupdivision** [comment]
Hello, thank you for using Creative Tim products.
I'm not sure I understand exactly what you need, is this it:
![image](https://user-images.githubusercontent.com/45566836/77679732-9fcf5300-6f9b-11ea-8d5a-4e0697b2d200.png)?

If so, just duplicate the content and change from col-md-12 to col-md-6.
Let me know if this helps.

All the best.

**Comment by bUniq-tech** [comment]
Nope, I mean two panels in same row, not two timelines. Like this:
![image](https://user-images.githubusercontent.com/60429781/78119653-0ecc0200-7409-11ea-9f99-0c55c74a0348.png)

**Comment by teamupdivision** [comment]
Hello, there is not default template created for this.
You can try to add an additional `<div class="timeline-panel">` element in the <li> parent.
You can add to the element another class to target it via css `<div class="timeline-panel right-panel">` .
Copy the css rules from the `.timeline-inverted` class children elements and target the `.right-panel` class.

All the best
