### ISSUE TITLE
Integration of Vue Material Pro template and an existing Laravel project

### ISSUE THREAD

**Issue by ForTraining-Projects** [creativetimofficial/ct-material-dashboard-pro-laravel#22]
Hello, I just bought and downloaded the Vue Material Dashboard Pro template and would like to integrate it into my existing Laravel project to be able to use Vue as my frontend. 
I already installed Vue as a dependency in my Laravel project. And now I would like to integrate all the pages and components provided by the Vue Material Dashboard Pro template. Is there any tutorial or manual how to do that the right way? 

I sent a message to the website support and they asked me to create an issue ticket here. 

Thank you for your reply.

Cheers Jens

**Comment by teamupdivision** [comment]
Hello @ForTraining-Projects, thank you for using our products.
We're working on this exact product at the moment, and we'll release it soon. Vue Material Dashboard integrated with Laravel API. You can start from scratch by building a Laravel API project and connecting it to the Vue.js one.

Right now I don't have any advice, the Material Laravel project is not meant for Vue.js, as it does not have an API. 

Stay tuned and and will soon launch our new product.

All the best

**Comment by ForTraining-Projects** [comment]
Hello, thank you for that update. Is there any chance you could tell me what 'soon' means? Do you have any roadmap? We are working on a web app and would like to use it asap. Thank you

**Comment by teamupdivision** [comment]
Hello, yes, we have a roadmap,
We will probably finish within a month, that is beginning of May.

Meanwhile, i you need help, or development services, please contact us here:
https://services.creative-tim.com/

**Comment by ForTraining-Projects** [comment]
Hello, regarding your Vue/Laravel roadmap for the Material Dashboard Pro. Is beginning of May still up-to-date?

**Comment by teamupdivision** [comment]
Hello, yes, I will let you know when we'll launch.
All the best.

**Comment by teamupdivision** [comment]
Hello, I wanted to let you know that we launched the Vue + Laravel project:
https://www.creative-tim.com/product/vue-material-dashboard-laravel-pro
