### ISSUE TITLE
Invalid login credentials shorten login form field to length 1

### ISSUE THREAD

**Issue by CraftyDlx** [creativetimofficial/ct-material-dashboard-pro-laravel#23]
Hello, I am working on a web app using Material Dash Pro and Laravel 7 and recognized that entering the wrong credentials leads to the side effect that the login field is shortened to length 1. You can check that easily out with the official template demo at creative Tim: https://www.creative-tim.com/live/material-dashboard-pro-laravel . Just enter a wrong login (e.g. "noone@none.net") and see yourself. Maybe I am missing something but I guess that's not how it should be. Thanks.

**Comment by teamupdivision** [comment]
Hello @CraftyDlx and thank you for using our products.
We'll follow up with a fix for this soonest.

All the best

**Comment by teamupdivision** [comment]
Hello @CraftyDlx  
The issue was fixed on both the demo and the download archive.
Thank you very much for your help.

**Comment by CraftyDlx** [comment]
Great, thanks! Could you provide some info how to fix / patch an existing Material Dash Pro web app?

**Comment by teamupdivision** [comment]
![image](https://user-images.githubusercontent.com/45566836/80375578-3647aa80-88a1-11ea-80a4-357d6fc79657.png)
