### ISSUE TITLE
Main page content not adjusting when fixed-top navbar changes height 

### ISSUE THREAD

**Issue by CraftyDlx** [creativetimofficial/ct-material-dashboard-pro-laravel#24]
I am using a fixed-top navbar with some nav-pill-icons. When the browser's width is changed manually by the user, the navbar increases it's height, because the nav-pill-icons arrange differently (how it's supposed to be). The problem is that the main page content (no matter what page), does not adjust to the height changes of the navbar. As a result, the main page's top content is hidden behind the navbar and not usable (there are not even scroll bars appearing for the main page). I would expect the main page content to slide down and adjust to the increased navbar height to maintain usability.
```
<nav class="navbar navbar-expand-sm fixed-top navbar-light bg-white ">
    <div class="container-fluid">     
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
            	<ul class="nav nav-pills nav-pills-danger nav-pills-icons justify-content-center" data-tabs="tabs" role="tablist" style="margin-right:20px";>
(...)
```

**Comment by CraftyDlx** [comment]
hello?

**Comment by groovemen** [comment]
Hello @CraftyDlx,

Thank you for using our products, we'll ask you to send us a code snippet with the navbar and the content to find a quick solution. Until then what you have to do is to change the **margin-top** property of the content; if you can see it has a `margin-top: 70px; `
<img width="247" alt="Screenshot 2020-05-04 at 14 29 27" src="https://user-images.githubusercontent.com/21063398/80961667-16ba0000-8e14-11ea-9940-be9848689fb8.png">
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by CraftyDlx** [comment]
The navbar version increasing height and hiding main page content when browser window decreases in width:
```
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white ">
    <div class="container-fluid">
    	<div class="my">
    		<a href="https://www.langer-e-technik.de/" target=_blank style="padding-left:10px;">{{ HTML::image("material/img/logo_langer-e-technik.png", "Logo") }}</a>
      </div>
        <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->     
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
            	<ul class="nav nav-pills nav-pills-danger nav-pills-icons justify-content-center" data-tabs="tabs" role="tablist" style="margin-right:20px";>

                    <li class="nav-item" style="padding-right:20px;">
               <a class="nav-link {{ Route::is('page.charts') || Route::is('home') ? 'active' : '' }}" data-toggle="link" href="{{ route('page.charts') }}" role="tablist" style="padding:1px;">
                        	<i class="material-icons">dashboard</i>Ressourcen</a>
                    </li>
                    <li class="nav-item" style="padding-right:20px;">
                <a class="nav-link {{ Route::is('page.notifications') ? 'active' : '' }}" data-toggle="link" href="{{ route('page.notifications') }}" role="tablist" style="padding:1px;">
                        	 <i class="material-icons">build</i>Vorgänge
                        </a>
                    </li>
            <li class="nav-item" style="padding-right:20px;">
               <a class="nav-link {{ Route::is('page.datatable_tables') ? 'active' : '' }}" data-toggle="link" href="{{ route('page.datatable_tables') }}" role="tablist" style="padding:1px;">
                    <i class="material-icons">format_list_bulleted</i>Log
                </a>
            </li>
             <li class="nav-item">
                <a class="nav-link {{ Route::is('user.index') ? 'active' : '' }}" data-toggle="link" href="{{ route('user.index') }}" role="tablist" style="padding:1px;">
                	<i class="material-icons">group</i>Benutzer</a> 
            </li>
            
            
            <li class="nav-item dropdown nav-pills-danger nav-pills-icons" role="tablist">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding:1px;">
                <i class="material-icons">person</i>Profil</a>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Benutzermanagement</a>
                
                <a class="dropdown-item" href="#">Profil bearbeiten</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Log Out</a>
              </div>
            </li>
                </ul>
            </div>
        </div>
 </div>
</nav>
```

**Comment by groovemen** [comment]
Hello again, 

You have to set this class `.navbar-absolute` for your navbar and it will look like this: 
<img width="1753" alt="Screenshot 2020-05-04 at 15 15 44" src="https://user-images.githubusercontent.com/21063398/80964903-5552b900-8e1a-11ea-8848-571f6d0c2cfb.png">

Also, you have to change the margin of the **content** to `margin-top: 100px;`

Best, 
Stefan

**Comment by CraftyDlx** [comment]
Added `navbar-absolute` to navbar tag and I changed the width in `public/material/css/material-dashboard.css` to 
```
.main-panel>.content {
  margin-top: 100px;
  padding: 30px 15px;
  min-height: calc(100vh - 123px);
}
```
and shows the effect that the main content has more distance to the navbar but it its still overlapping when the navbar height increases, the main content is not moving down to be useable and readable. Did not work, there must be something else?

**Comment by groovemen** [comment]
Hello again, 

Then you have to change the position of the navbar. By setting the class **.fixed-top**, it gets `position: fixed;` so please set `position: relative;` and erase class **fixed-top**.

Cheers, 
Stefan

**Comment by CraftyDlx** [comment]
So you're telling me the Material Pro template does not support fixed, growing navbars without losing the usability of the main page? Hard to believe.

**Comment by CraftyDlx** [comment]
I am still waiting for a solution here. What groovemen (Stefan) suggested, not using a feature to avoid flawed functionality, can't be taken seriously of course.

**Comment by groovemen** [comment]
First of all, I will ask you to send us your orderID or a reference to check something. Secondly, please tell me that my suggestion by erasing the **fixed-top** and **navbar-absolute** classes, messed up your navbar by getting "_flawed functionality_". 

You asked for a solution for the navbar: if it's increasing the height then the main content to move down. This is what will happen if you will erase those classes.

**Comment by CraftyDlx** [comment]
You should be less keen for formalities and admonitions and much more keen for providing useable hints and solutions. The latter keeps customers near and trouble away -- the other does the contrary. That's guaranteed.

My client wants a fixed navbar to the top and this is for sure not an exotic feature but pretty much standard. Your "solution" is not a solution, it is avoidance. 

I ask you again: Does the Material Pro Template of Creative Tim provide fixed, growing navbars without losing the usability of the main page or not?

**Comment by groovemen** [comment]
Hello again, 

I'm sorry that the above solution was in vain but I later thought that maybe I should have been more explicit in terms of reporting a solution.

So, let's say you deleted `navbar-absolute` and you didn't delete `position-top` but you want to have a navbar with `position: fixed` so you won't be able to have the content below it scalable, ie it won't go down if the height of the navbar increases. Instead, if you set for navbar` position: relative `will behave according to your requirements.

I told you to erase the **fixed-top** class because it has the following properties that you can get rid of
<img width="139" alt="Screenshot 2020-05-06 at 14 50 01" src="https://user-images.githubusercontent.com/21063398/81173531-df308c80-8fa8-11ea-891b-11822de6d893.png">

To make things more clear, erase **navbar-absolute** class and set `position-relative` for the navbar and it should work as expected.
I will make a video if this explanation doesn't make things clear. 

Cheers, 
Stefan

**Comment by CraftyDlx** [comment]
No, replacing `position:fixed` for `position:relative` in the css moves the page down when navbar increases height **but does not keep the navbar fixed.**  My css part:
```
.fixed-top {
  position: relative;
  top: 0;
  right: 0;
  left: 0;
  z-index: 1030;
}
```
My navbar:
```
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white ">
    <div class="container-fluid">
    	<div class="my">
    		<a href="https://www.company.com/" target=_blank style="padding-left:10px;">{{ HTML::image("material/img/mylogo.png", "Logo") }}</a>
      </div>
        <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->     
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
            	<ul class="nav nav-pills nav-pills-danger nav-pills-icons justify-content-center" data-tabs="tabs" role="tablist" style="margin-right:20px";>
(...)
```
Does it work on your side? If yes, what is the difference to your code?

**Comment by groovemen** [comment]
Hello again,

As I told you above you can't achieve the expected behavior just by erasing or adding position for the navbar. The concern with fixed positioning is that it can cause situations where the fixed element overlaps content such that is is inaccessible. 
Please read and understand all the CSS Positioning: https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/

I understand what you need so you will have to create a JavaScript that measures the navbar height and set a padding for the content for positioning it below the navbar (no matter the height of it). Please keep this in mind that we cannot help you with that, since it falls into custom development, and not in our support attributions.

For custom development, please refer to our colleagues here: https://services.creative-tim.com/?ref=support

Best, 
Stefan

**Comment by CraftyDlx** [comment]
> The concern with fixed positioning is that it can cause situations where the fixed element overlaps content such that is is inaccessible.
I am really wondering why you did not tell me that in your first post. No offense, but that would have saved a lot of time. I assumed this is just a standard feature Bootstrap can do off the box.

> Please read and understand all the CSS Positioning: https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/
I am very familiar with CSS. What I am not familiar with is the ongoing in the background of your templates and Bootstrap JS. 

> I understand what you need so you will have to create a JavaScript 
Thanks, I really appreciate that. I don't expect Creative Tim to do the coding for me. Maybe you should mention this behaviour in the docs of your template. I searched both template and Bootstrap docs for quite a time and did not find a word about this problem.
