### ISSUE TITLE
An issue with calendar

### ISSUE THREAD

**Issue by janbaker0901** [creativetimofficial/ct-material-dashboard-pro-laravel#26]
When I click a scheduled item, the details isn't open.
And when I create a new schedule, I can't set color.
Can you tell me about that?

**Comment by teamupdivision** [comment]
Hello and thank you for using our products!
Are you referring to the calendar page?

All the best

**Comment by janbaker0901** [comment]
Thanks for your reply.
Yes, I am using Calendar page.
I think what I asked is a basic function.
I thought the features would have been reflected in your product.

**Comment by janbaker0901** [comment]
And there is one more question.
I uploaded the user avatar on the Profile page and clicked the Update button, http: // localhost: 8000 / storage / profile / mKyAOIzW5xoEhMIkbFQRHuDv6qjJh5TN38rtvnyE.jpeg is creating a 404 Error
I have run php artisan storage: link and have already received a notification that public / storage is connected to stoarge / app / public.
I've read many articles to solve this, but couldn't find a solution.
I am working on local now.
I need your help.
To solve this I am spending too much time.

**Comment by teamupdivision** [comment]
Hello,

Regarding the calendar was integrated like that, without colors, and without popping up existing events. In the future we might implement another calendar plugin: https://fullcalendar.io/

On the image upload issue, are working on Linux or Windows? Also, are you working on Material PRO or FREE?

Thank you
