### ISSUE TITLE
Unwanted indention on Email form field alert message

### ISSUE THREAD

**Issue by CraftyDlx** [creativetimofficial/ct-material-dashboard-pro-laravel#27]
In my form the alert message for invalid or missing Email has an (to me unexplainable) indention to the right (see image attached, I also put a border to the alert message to make it more clear). I am using the code below and did not change anything in the `/resources/lang/en/validation.php`. The other alert messages do not have this issue.

```
<div class="row">
   <label class="col-sm-2 col-form-label">{{ __('Login') }}</label>
   <div class="col-sm-7">
      <div class="form-group{{ $errors->has('userid') ? ' has-danger' : '' }}">
         <input class="form-control{{ $errors->has('userid') ? ' is-invalid' : '' }}" name="userid" id="input-login" type="text" placeholder="{{ __('') }}" value="{{ old('userid', $user->userid) }}" aria-required="true"/>
         @include('alerts.feedback', ['field' => 'userid'])
      </div>
   </div>
</div>
<div class="row">
   <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
   <div class="col-sm-7">
      <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
         <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" id="input-email" type="text" placeholder="{{ __('') }}" value="{{ old('email', $user->email) }}" aria-required="true"/>
         <div class="showme">@include('alerts.feedback', ['field' => 'email'])</div>
      </div>
   </div>
</div>
<style>
.showme{
  border: 1px solid black;
}	
</style>
  
```

![Screen Shot 05-20-20 at 01 06 PM](https://user-images.githubusercontent.com/59885175/82440008-ede46c80-9a9b-11ea-9313-0cbcf68a498c.PNG)

**Comment by teamupdivision** [comment]
Hello, thank you for using our products.

Please go edit /css/material-dashboard.css

Replaace this code:
`#email-error{
    height:30px;
    margin-left:54px;
}`

With this:
`.card.card-login #email-error{
    height:30px;
    margin-left:54px;
}
.card.card-login #password-error{
    height:30px;
    margin-left:54px;
}`

**Comment by CraftyDlx** [comment]
Thanks, it worked. Was this a bug and is fixe, so that I can safely update in future versions?

**Comment by teamupdivision** [comment]
It's bug, and it will also be updated in the future version.
