### ISSUE TITLE
Dropdown menu increases length below media: width 992px

### ISSUE THREAD

**Issue by CraftyDlx** [creativetimofficial/ct-material-dashboard-pro-laravel#29]
When width changes by browser below 992px width, a useless scrollbar appears and the dropdown menu gains length (see images). I did not do any changes to dropdown menu or items css. 

Correct dropdown menu length:

![Screen Shot 05-25-20 at 10 48 PM](https://user-images.githubusercontent.com/59885175/82842497-0e685880-9eda-11ea-9907-47f53ced4d5f.PNG)

 Below 992px width: Dropdown menu length increased and scrollbar:

![Screen Shot 05-25-20 at 10 47 PM](https://user-images.githubusercontent.com/59885175/82842514-217b2880-9eda-11ea-8e37-293cd5a08e84.PNG)

**Comment by teamupdivision** [comment]
Hello, are you talking about the top main menu?
The demo dashboard https://material-dashboard-pro-laravel.creative-tim.com/dashboard work just fine with changing the window size.

**Comment by CraftyDlx** [comment]
The demo dashboard has no dropdown menu showing below 800px width, because it collapses.

**Comment by groovemen** [comment]
Hello again @CraftyDlx,

You can try to set a `height: auto` property for the dropdown. After that, it should look like in your first image.
Cheers,
Stefan
