### ISSUE TITLE
Cartist and Laravel 

### ISSUE THREAD

**Issue by WoutervanderHorst** [creativetimofficial/ct-material-dashboard-pro-laravel#3]
Hello,

I will change the charts from the template to a mysql table.

Can everybody tell me where i can change the demo data and help to more information how to setup to database data?

First i will ask where can i change the demo data of the default charts in dashboard.

**Comment by Ghitu** [comment]
Hello @WoutervanderHorst, thanks for using our products!
The charts are done with https://www.chartjs.org/.
You can check their docs here https://www.chartjs.org/docs/latest/

Best
Eugen

**Comment by WoutervanderHorst** [comment]
Hello Eugen,

Thank you for answer. Nice that it's chartjs.org.
On the website and in the documentation you still refer to chartist.org, perhaps you can adjust this

Best Regards,

Wouter

**Comment by Ghitu** [comment]
Hello @WoutervanderHorst, thank you very much for the suggestion.
Glad we could be of help. All the best!
