### ISSUE TITLE
Wrong download file

### ISSUE THREAD

**Issue by roenfeldt** [creativetimofficial/ct-material-dashboard-pro-laravel#30]
It's not an issue related to the framework itself, but rather a problem that's occurring when trying to download the Laravel .zip file. Basically, a different product will start downloading upon clicking the Download button in the **/downloads** section. Please fix this issue, so that the appropriate file can be downloaded. Thank you.

<img width="1335" alt="Screen Shot 2020-06-15 at 13 53 34" src="https://user-images.githubusercontent.com/60813178/84655160-ba68f680-af10-11ea-95df-ad85da13217f.png">

**Comment by teamupdivision** [comment]
Hello Daniel, many thanks for using Creative Tim products.
Thank you for your feedback, we've fixed the issue.
All the best
