### ISSUE TITLE
Selectpicker is not showing a placeholder - unless I remove the selectpicker class

### ISSUE THREAD

**Issue by SimonGuitarJackson2020** [creativetimofficial/ct-material-dashboard-pro-laravel#31]
Hi guys,

I'm trying to get a placeholder that says 'Please choose a level ...' in my selectpicker.
The following code works fine if I remove the selectpicker class - the input shows with the 'Please choose a level ...' and then when I click and choose an option these words disappear from the list - as it should be.  But if I include the selectpicker class to get the styling I want it does not anything until I click the input.

Here's my code:

`<select name="level_id" type="text" id="level_id" class="form-control selectpicker mb-3" data-style="btn btn-link btn-primary" placeholder="Please choose a level ..">
      <option value="" disabled selected hidden>Please choose a level</option>
      @foreach($levels as $level)
              <option value="{{ $level->id }}">{{ $level->id }}. {{ $level->description }}</option>
      @endforeach
</select>`

Am I doing something wrong?  I have checked at https://demos.creative-tim.com/marketplace/material-kit-pro/docs/2.1/components/forms.html . 

Thanks in advance.

**Comment by teamupdivision** [comment]
Hello, thank you for using our products!
Please checkout this link: https://demos.creative-tim.com/marketplace/material-kit-pro/docs/2.1/plugins/select-bootstrap.html

In order to put placeholder text you should use title=“placeholder text”
