### ISSUE TITLE
File Input Doesn't Work

### ISSUE THREAD

**Issue by armand0sosa** [creativetimofficial/ct-material-dashboard-pro-laravel#33]
The file input doesn't work even on you page:

```
<div class="form-group form-file-upload form-file-multiple">
    <input type="file" multiple="" class="inputFileHidden">
    <div class="input-group">
        <input type="text" class="form-control inputFileVisible" placeholder="Single File">
        <span class="input-group-btn">
            <button type="button" class="btn btn-fab btn-round btn-primary">
                <i class="material-icons">attach_file</i>
            </button>
        </span>
    </div>
  </div>

```
Your page URL:
https://material-dashboard-pro-laravel.creative-tim.com/docs/components/forms.html

**Comment by teamupdivision** [comment]
Hello @armand0sosa,

Thanks for using our products.

If what you are saying is that section has no backend functionality, that is true, First of all those are the docs and they're just code samples.

Real workign examples can be found in the Laravel examples in the product demo, please go to this link: https://material-dashboard-pro-laravel.creative-tim.com/  - submit the login form - and then go to https://material-dashboard-pro-laravel.creative-tim.com/item - where you can manabe a working form example of a file input upload.

If you have any more questions, feel free to reopen this issue or create another one.

All the best

**Comment by armand0sosa** [comment]
In the free version this works but in the pro version it doesn't work.

I need to use it, how can I made this work? And I don't mean the backend, I mean the simple act of clicking on it and selecting the file.

Free Version URL (Working):
https://material-dashboard-laravel.creative-tim.com/docs/components/forms.html

Pro Version URL (Not Working):
https://material-dashboard-pro-laravel.creative-tim.com/docs/components/forms.html

**Comment by teamupdivision** [comment]
Hello,
thanks for using our product!
We'll follow up with a solution tomorrow.
All the best

**Comment by teamupdivision** [comment]
Hello,
We've commited a solution to the problem you posted.
Please download the product again from the download section.

Feel free to follow up if any other issues arise.

All the best

**Comment by armand0sosa** [comment]
Thank you, I already downloaded it and it still doesn't work, I thought it was a cache problem, but it isn't.

I also just checked the documentation page and it does work there, but it has an error, it opens the window to select the file twice.

**Comment by teamupdivision** [comment]
Hello,

Please check again now.
You can also check the docs page.

Thank you

**Comment by armand0sosa** [comment]
Thank you, now it works.

But is there any way to update without having to redownload the entire file and start a new project? Because I already have a slightly advanced project with the template and I should re-create my models, views and controllers again.

**Comment by teamupdivision** [comment]
Hello, see in the images attached the two files that were updated and the exact code lines you need to copy from the archive.
![image](https://user-images.githubusercontent.com/45566836/106238220-1d41a080-6209-11eb-9aee-a9a16543c21b.png)
![image](https://user-images.githubusercontent.com/45566836/106238248-2a5e8f80-6209-11eb-8aa5-eb9fc535d50f.png)

**Comment by armand0sosa** [comment]
Thank you so much!
