### ISSUE TITLE
Issue when copying the code from Category Management to build another identical module. 

### ISSUE THREAD

**Issue by arvindcletus** [creativetimofficial/ct-material-dashboard-pro-laravel#35]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I'm trying to create a module called Class Management by mirroring the code from Category Management. Everything works except for the edit and destroy routes. 

# Current Behavior

What is the current behavior?

The index route works fine and I am able to view the table but the edit and delete routes throw me to a 403 page.

**Comment by teamupdivision** [comment]
Hi @arvindcletus,

Thank you for using Creative Tim products and posting the updates for your issue. 

If you have my other problems, please feel free to let us know.

All the best,
UPDIVISION Team

PS: If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
