### ISSUE TITLE
Edit in new CRUD forbidden

### ISSUE THREAD

**Issue by SolutionsDesk** [creativetimofficial/ct-material-dashboard-pro-laravel#36]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [. ] I am running the latest version
- [ .] I checked the documentation and found no answer
- [. ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I expect to be able to access the edit page of a new model/ crud. Receiving a 403 Forbidden

# Current Behavior

What is the current behavior?
I created a new model for KenyaPage, created both Policy & Requests/KenyaPageRequest . I have also implemented in the controller for the model including the authorize resource in the construct. I am able to view all, create but after creation when trying to access edit I get a 403 Forbidden. 

Validation rules are working. I have confirmed on creation. 
I also created a new role and added it under the User Model like the existing roles. It is working and given access, however the  403 error is produced no matter the rights given. 

Items create, edit and update are all working fine. 

If I go the middleware route in the web routes and exclude any of the Validation or Authentication setup as default I can create, edit, update and view all without any issues.

## Steps to Reproduce

# 1 Created model for KenyaPage

/**

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KenyaPage extends Model
{
    use HasFactory;
    use Sluggable;
    use SoftDeletes;
    protected $dates = [ 'deleted_at' ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

     protected $fillable = [
             'country_id','slug','title', 'body','featured_image','status', 'meta_title', 'meta_description', 'mobile_feature_image', 'template_name', 'date'
         ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'array',
    ];

}
'

# 2 Created the Policy KenyaPagePolicy 

'

namespace App\Policies;

use App\KenyaPage;
use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class KenyaPagePolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     *
     * @param  \App\User  $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
        return true;
    }

    /**
     * Determine whether the user can view the model.
     *
     * @param  \App\User  $user
     * @param  \App\KenyaPage  $kenyaPage
     * @return mixed
     */
    public function view(User $user, KenyaPage $kenyaPage)
    {
        return $user->isAdmin() || $user->isCreator();
    }

    /**
     * Determine whether the user can create models.
     *
     * @param  \App\User  $user
     * @return mixed
     */
    public function create(User $user)
    {
        return $user->isAdmin() || $user->isCreator();
    }

    public function edit(KenyaPage $item){
        return $user->isAdmin() || $user->isCreator();
    }

    /**
     * Determine whether the user can update the model.
     *
     * @param  \App\User  $user
     * @param  \App\KenyaPage  $kenyaPage
     * @return mixed
     */
    public function update(User $user, KenyaPage $item)
    {
        return $user->isAdmin() || $user->isCreator();
    }

    /**
     * Determine whether the user can delete the model.
     *
     * @param  \App\User  $user
     * @param  \App\KenyaPage  $kenyaPage
     * @return mixed
     */
    public function delete(User $user, KenyaPage $item)
    {
        return $user->isAdmin() || $user->isCreator();
    }

    /**
     * Determine whether the user can restore the model.
     *
     * @param  \App\User  $user
     * @param  \App\KenyaPage  $kenyaPage
     * @return mixed
     */
    public function restore(User $user, KenyaPage $item)
    {
        return $user->isAdmin() || $user->isCreator();
    }

    /**
     * Determine whether the user can permanently delete the model.
     *
     * @param  \App\User  $user
     * @param  \App\KenyaPage  $kenyaPage
     * @return mixed
     */
    public function forceDelete(User $user, KenyaPage $item)
    {
        return $user->isAdmin();
    }
}

'
# 4 I then created the Request / KenyaPageRequest with a very basic rule to test

'

namespace App\Http\Requests;

use App\KenyaPage;
use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;

class KenyaPageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => ['required', 'min:5'],
        ];
    }

}
'
# 5 I added the class to the $policies 

'
namespace App\Providers;

use App\KenyaPage;
use App\Tag;
use App\Item;
use App\Role;
use App\User;
use App\Category;
use App\Policies\TagPolicy;
use App\Policies\ItemPolicy;
use App\Policies\RolePolicy;
use App\Policies\UserPolicy;
use App\Policies\CategoryPolicy;
use App\Policies\KenyaPagePolicy;
use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        User::class => UserPolicy::class,
        Category::class => CategoryPolicy::class,
        Item::class => ItemPolicy::class,
        Role::class => RolePolicy::class,
        Tag::class => TagPolicy::class,
        KenyaPage::class => KenyaPagePolicy::class,
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Gate::define('manage-items', 'App\Policies\UserPolicy@manageItems');

        Gate::define('manage-users', 'App\Policies\UserPolicy@manageUsers');
    }
}
'
# 6 I then added to the Controller 

'

namespace App\Http\Controllers;

use App\KenyaPage;
use App\Http\Requests\KenyaPageRequest;
//use Illuminate\Http\Request;

class KenyaPageController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(KenyaPage::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
  /*  public function index()
    {
        $pages = KenyaPage::orderBy('title', 'asc')->get();
        return view('app-pl.pages.kenya.index_new', compact(['pages']));
    }
  */
    public function index(KenyaPage $model)
    {
        return view('app-pl.pages.kenya.index_new', ['items' => $model->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app-pl.pages.kenya.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
  

    public function store(KenyaPageRequest $request, KenyaPage $model)
    {
        $page = $model->create($request->all());

        return redirect()->route('kenya.edit', $page->id)->withStatus(__('Item successfully created.'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit(KenyaPage $page)
    {
        return 'Working';
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KenyaPageRequest $request, KenyaPage $page)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(KenyaPage $page)
    {
        //
    }
}
'

Hopefully someone will spot any step I may have missed. I am currently only at the learning stage of working with Material

**Comment by teamupdivision** [comment]
Hi @SolutionsDesk,

Thank you for reporting this and for using Creative Tim products.

Can you please check if you can remove your edit function from Policy? The update function is for both methods, update and edit from the controller.

![unknown](https://user-images.githubusercontent.com/45566836/120650335-5bd0bb80-c486-11eb-8c43-a53e396bde4d.png)

https://laravel.com/docs/8.x/authorization

Please let us know if this helped or if there is anything else.

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @SolutionsDesk, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @SolutionsDesk, 

Just checking if there is anything else we can help with and if the issue above has been solved. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @SolutionsDesk,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
