### ISSUE TITLE
php artisan migrate --seed >> Give exception error

### ISSUE THREAD

**Issue by yukeshean** [creativetimofficial/ct-material-dashboard-pro-laravel#37]
php artisan key:generate 
Result: Application key set successfully.

php artisan migrate --seed

Result:
Migrating: 2014_10_12_100000_create_password_resets_table

   Illuminate\Database\QueryException

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' already exists (SQL: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at C:\FOOYS_HOME\prog\material-dashboard\vendor\laravel\framework\src\Illuminate\Database\Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

**Comment by teamupdivision** [comment]
Hi @yukeshean,

Thank you for reporting this issue and for using Creative Tim products.

The error appears as the database for this seed already exists.

Please try:  `php artisan migrate:fresh --seed`

Let us know if this worked or if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @yukeshean, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @yukeshean,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
