### ISSUE TITLE
Additional roles not available

### ISSUE THREAD

**Issue by RodneyMiller** [creativetimofficial/ct-material-dashboard-pro-laravel#39]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting.

I've reported this before but I can't add new roles. I've downloaded the Pro Version from the Creative Tim Website.

![image](https://user-images.githubusercontent.com/29591445/161487727-6bad8477-7dce-4944-a5c0-84c3220e1e71.png)

# Current Behavior

There are only 3  roles available.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

I've downloaded and installed it multiple times as per the instructions but no changes.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 11
* Browser and Version: Chrome 100.0.4896.60 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by RodneyMiller** [comment]
I've downloaded and installed:

- black-dashboard-pro-laravel
- material-dashboard-pro-laravel
- now-ui-dashboard-pro-laravel
- white-dashboard-pro-laravel

And all have the same issue.

**Comment by teamupdivision** [comment]
Hi @RodneyMiller,

Thanks for reporting this and for using Creative Tim products.

The add roles functionality has been removed, but you can add it back easily. The steps you need to follow are:
1. Add a button in the resources/roles/index.blade.php Add Role ( for reference check the index.blade.php of tags) with the href={{route('role.create')}}
2. Go to RoleController and uncomment the create function and the store function
3. Go to web.php file and in the auth middleware on  Route::resource('role', 'RoleController', ['except' => ['show', 'destroy','create']]); delete 'create'

Please let us know if this helped and if there is any other info needed.

Best,
UPDIVISON Team

**Comment by RodneyMiller** [comment]
Thanks heaps team.

That worked

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by teamupdivision** [comment]
Hi @RodneyMiller,
 
We're glad to hear that! We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
