### ISSUE TITLE
Email Verification - Undefined variable $menuParent

### ISSUE THREAD

**Issue by nelsonopazo** [creativetimofficial/ct-material-dashboard-pro-laravel#40]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

mail verification

# Current Behavior

ErrorException

Undefined variable $menuParent

# Failure Information (for bugs)

email verification setup

## Steps to Reproduce

1. step 1
add in user model implements

class User extends Authenticatable implements MustVerifyEmail

2. step 2
add in route web.php activate the verification

Auth::routes(['verify' => true]);

3. step 3
add the routes in web.php

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
  $request->fulfill();

  return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
  $request->user()->sendEmailVerificationNotification();

  return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Route::get('profile', function () {
  // Only verified users may access this route...
})->middleware('verified');

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: 
* Operating System: Windows 11
* Browser and Version: Chrome last version
PHP 8.1.6
9.4.1

## Failure Logs

C:\laragon\www\lunes\storage\framework\views\57927f07a96c34e93e489eebbeb7b2cd78508409
.php 

linea : 55

                <span class="sidebar-mini"> S </span>

                <span class="sidebar-normal"> Settings </span>

              </a>

            </li>

          </ul>

        </div>

      </div>

    </div>

    <ul class="nav">

      <li class="nav-item<?php echo e($activePage == 'dashboard' ? ' active' : ''); ?>">

        <a class="nav-link" href="<?php echo e(route('home')); ?>">

          <i class="material-icons">dashboard</i>

            <p><?php echo e(__('Dashboard')); ?></p>

        </a>

      </li>

      

      <li class="nav-item">

        

        <a class="nav-link" data-toggle="collapse" href="#laravelExample">

          <i><img style="width:25px" src="<?php echo e(asset('material')); ?>/img/laravel.svg"></i>

          <p><?php echo e(__('Laravel Examples')); ?>

            <b class="caret"></b>

          </p>

        </a>

        <div class="collapse<?php echo e(($menuParent == 'dashboard' || $menuParent == 'laravel') ? ' show' : ''); ?>" id="laravelExample">

          <ul class="nav">

            <li class="nav-item<?php echo e($activePage == 'profile' ? ' active' : ''); ?>">

              <a class="nav-link" href="<?php echo e(route('profile.edit')); ?>">

                <span class="sidebar-mini"> UP </span>

--------------------

Controller
App\Http\Controllers\Auth\VerificationController@show

Route name
verification.notice

Middleware
web

auth

----------------------

View
C:\laragon\www\lunes\resources\views\layouts\navbars\sidebar.blade
.php
Data
errors
Illuminate\Support\ViewErrorBag {#1256 ▼
  #bags: []
}
class
"off-canvas-sidebar"
classPage
"login-page"
activePage
"verify"
title
"Material Dashboard"
pageBackground

**Comment by teamupdivision** [comment]
Hi @nelsonopazo,

Thank you for using the Creative Tim products.

You seem to have an issue with the menuParent variable. You can try deleting it to see what happens.

Best,
UPDIVISION Team
