### ISSUE TITLE
Unable to compile custom stylesheet from SCSS using Laravel-mix

### ISSUE THREAD

**Issue by SolutionsDesk** [creativetimofficial/ct-material-dashboard-pro-laravel#42]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I am trying to compile the material-dashboard.scss to a css file with my custom styles included. No custom styles added. I am trying with the exact files shipped with Material laravel dashboard pro 2 (Material Dashboard Pro - v3.0.1 scss)

# Current Behavior
Laravel-mix & Code Kit throw errors. On Code Kit, it says the use of depreciated DartSASS and similiar is LibSass is used. Below is the Laravel mix error.

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compiling the shipped webmix file results in a blank css file.
2. set laravel mix to mix.sass('public/assets/scss/material-dashboard', 'public/assets/css/test.css');
3. npm run dev or npm run watch
4. Compiling start and gets to +/- 30% then it throws the error listed below. 
5. I have tried thing using the CodeKit compiler & the Laravel-mix. Laravel-mix is used for all Material Laravel Dashboard Pro builds, without issues in the past.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: M1 Mackbook Pro
* Operating System: Monterey 12.6
* Browser and Version: Brave, Chrome, Firefox, Safari ...all latest

## Failure Logs

> npm run dev

> development
> mix

✖ Mix
Compiled with some errors in 2.03s

ERROR in ./resources/scss/material-dashboard.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
╷
15 │   &.bg-gradient-faded-#{$prop}-vertical{
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
resources/scss/material-dashboard/_gradients.scss 15:3  @import
resources/scss/material-dashboard/theme.scss 43:9       @import
resources/scss/material-dashboard/theme-pro.scss 20:9   @import
resources/scss/material-dashboard.scss 27:9             root stylesheet
at processResult (/Users/michaelburton/current-work/TopNutDev2022/node_modules/webpack/lib/NormalModule.js:758:19)
at /Users/mb/current-work/TopNutDev2022/node_modules/webpack/lib/NormalModule.js:860:5
at /Users/mb/current-work/TopNutDev2022/node_modules/loader-runner/lib/LoaderRunner.js:400:11
at /Users/mb/current-work/TopNutDev2022/node_modules/loader-runner/lib/LoaderRunner.js:252:18
at context.callback (/Users/mb/current-work/TopNutDev2022/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
at Object.loader (/Users/mb/current-work/TopNutDev2022/node_modules/sass-loader/dist/index.js:69:5)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors

**Comment by teamupdivision** [comment]
Hello,

Thank you for using creative TIM products. 

We are looking into the issue and will get back to you as soon as possible.

Thank you.

**Comment by SolutionsDesk** [comment]
Thank you so much.

**Comment by teamupdivision** [comment]
Hello, 

Sorry for the big delay in response. 

Has the issue been resolved? 

Thank you.
