### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by cyberautomate** [creativetimofficial/ct-material-dashboard-pro-laravel#43]
# Current Behavior
I get the attached database error when running the migrations via `php artisan migrate --seed`
![image](https://user-images.githubusercontent.com/95773446/206061823-7a1c3538-4e01-419f-90f0-6d9e2793a5f7.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

I tried resetting the migrations and got the same result. I also deleted and re-created the database and get the same error.

* Latest version of Laravel
* Latest version of the template downloaded just before installation

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products!

You could try the "php artisan migrate:fresh --seed" command, but please keep in mind that it will reset your data base and it will add the data from seeding. 

If this does not work, could you please give us more details? Did you make sure to follow all the steps or did you make any changes to the project?

Thank you.

**Comment by cyberautomate** [comment]
I followed the install instructions listed here: https://github.com/creativetimofficial/ct-material-dashboard-pro-laravel#installation

I re-created a new database, I'm using a brand new installation of Laravel (Laravel new site), nothing else has been add other than the template files.

Run php artisan migrate: fresh --seed and get the following error
![image](https://user-images.githubusercontent.com/95773446/206187911-d0c4da57-5227-4323-8c7a-106d136c1c9f.png)

These tables are created when the migration runs. Just have no users, all the tables are empty.
![image](https://user-images.githubusercontent.com/95773446/206188214-35cf5aa7-1baf-4d8f-a88e-75efd5dd2453.png)

**Comment by teamupdivision** [comment]
Hello,

From what we can see you have Laravel breeze and not Laravel, could you install Laravel and let us if the issue still persists? 

Thank you.

**Comment by cyberautomate** [comment]
You're correct, that was my fault. I was copying the contents of the template into a baseline Laravel project. Worked fine when I did it correctly. Sorry for the confusion and thank you for the support
