### ISSUE TITLE
When i open Bootstrap Modal i can not prevent background scroll

### ISSUE THREAD

**Issue by kaangrbz** [creativetimofficial/ct-material-dashboard-pro-laravel#44]

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products!

Try adding on your body tag the overflow: hidden when your modal is open using vaniila JS, jQeury or AlpineJS. 

You can check this example https://www.geeksforgeeks.org/how-to-prevent-body-from-scrolling-when-a-modal-is-opened-using-jquery/#:~:text=Approach%3A%20A%20simple%20solution%20to,scroll%20on%20the%20selected%20element.

 If this isn't working, please share the components where you are trying to use it and how you are using it.
 
 Thank you.
