### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by koltz** [creativetimofficial/ct-material-dashboard-pro-laravel#6]
Just before, I installed the free version without an issue, but I purchased the Pro version and I get this issue below.

I am installing Material Pro Laravel and I get to the "php artisan migrate --seed" part of the installation and I get an error:

 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function str_random()

at /var/www/material/database/factories/UserFactory.php:23
    19|         'name' => $faker->name,
    20|         'email' => $faker->unique()->safeEmail,
    21|         'email_verified_at' => now(),
    22|         'password' => Hash::make('secret'), // secret
  > 23|         'remember_token' => str_random(10),
    24|         'role_id' => 3,
    25|         'created_at' => now(),
    26|         'updated_at' => now()
    27|     ];

  Exception trace:

  1   Illuminate\Database\Eloquent\Factory::{closure}(Object(Faker\Generator), ["Admin", "admin@material.com"])
      /var/www/material/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:274

  2   call_user_func(Object(Closure), Object(Faker\Generator), ["Admin", "admin@material.com"])
      /var/www/material/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:274

**Comment by koltz** [comment]
Looks to be related to this link with Laravel 5.8 and newer,

https://medium.com/@advanceidea/laravel-5-8-620b007fdd9d -Deprecated String and Array Helpers Functions

**Comment by koltz** [comment]
Changing the line referenced from:

'remember_token' => str_random(10),

to

'remember_token' => Str::random(10),

Seems to work.

**Comment by teamupdivision** [comment]
Hello @koltz 
Thank you for the issue report.
We also made a fix to the download archive.
Thank you for your help.
