### ISSUE TITLE
 Template colors

### ISSUE THREAD

**Issue by jeasomoza** [creativetimofficial/ct-material-dashboard-pro-laravel#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [ YES] I checked to make sure that this issue has not already been filed
- [ YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Quisiera cambiar los colores de la platilla a mis colores corporativos, a travez de las clases ejem. "info", "success", "danger", "warning"

# Current Behavior

I put a button:

`<button class = "btn btn-success"> Success </button>`

And it appears green and I want it to appear with the color: # FF4406

# Failure Information (for bugs)

In which file did this change?

**Comment by teamupdivision** [comment]
Hello. here is the docs regarding buttons https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/components/buttons.html#style-buttons 
You can override the colors directly in the CSS file, or include your own CSS file and write the overriding code there.
